version: '3'
services:
  nginx:
    build: ./nginx
    container_name: my-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
      - /home/marci:/home/marci
    ports:
      - 80:80
      - 443:443

  # webhook-agent:
  #   volumes:
  #     - ./pipe:/hostpipe

  sm-lang:
    build: ./sm-lang
    container_name: sm-lang
    expose:
      - '80'

  vacskamati.hu:
    build: ./vacskamati.hu
    container_name: vacskamati.hu
    expose:
      - '80'

